version: "3"
networks:
    proxy:
        driver: bridge
services:
    grpc-client:
        container_name: grpc-client
        build:
            context: .
            args:
                - SERVICE=start-grpc-client.sh
        image: grpc-client:latest
        restart: always
        networks:
            - proxy
        volumes:
            - ${GOPATH}/src/github.com/chrispaynes/gRPCrud:${GOPATH}/src/github.com/chrispaynes/gRPCrud
    grpc-server:
        container_name: grpc-server
        build:
            context: .
            args:
                - SERVICE=start-grpc-server.sh
        image: grpc-server:latest
        restart: always
        networks:
            - proxy
        ports:
            - "9090:9090"
        volumes:
            - ${GOPATH}/src/github.com/chrispaynes/gRPCrud:${GOPATH}/src/github.com/chrispaynes/gRPCrud
    postgres:
        container_name: grpcrud-postgres
        build:
            context: .
            dockerfile: ./docker/postgres/postgres.dockerfile
        image: grpcrud-postgrest:latest
        restart: always
        networks:
            - proxy
        env_file:
            - ${GOPATH}/src/github.com/chrispaynes/gRPCrud/docker/postgres/postgres.env
        ports:
            - "5432:5432"
        volumes:
            - ${GOPATH}/src/github.com/chrispaynes/gRPCrud/docker/pgdata:/var/lib/postgresql/data
