// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo-service.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Todo                 *Todo    `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Todo)(nil), "v1.Todo")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
}

func init() { proto.RegisterFile("todo-service.proto", fileDescriptor_80b701c7b1c502fe) }

var fileDescriptor_80b701c7b1c502fe = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x6a, 0xf3, 0x30,
	0x10, 0x86, 0xf1, 0xcf, 0x17, 0x92, 0x31, 0x5f, 0x68, 0x87, 0x2e, 0x8c, 0x29, 0xd4, 0x78, 0xe5,
	0x4d, 0x65, 0xe2, 0x42, 0x97, 0xed, 0xa2, 0x37, 0x50, 0x73, 0x01, 0x27, 0x9a, 0x06, 0x41, 0xec,
	0x71, 0x25, 0xc5, 0x47, 0xe8, 0xb9, 0x8b, 0x25, 0x5c, 0x52, 0xe8, 0x4e, 0x7a, 0x35, 0x3c, 0x7a,
	0xde, 0x01, 0x74, 0xac, 0xf8, 0xd1, 0x92, 0x99, 0xf4, 0x91, 0xc4, 0x68, 0xd8, 0x31, 0xc6, 0xd3,
	0xae, 0x78, 0x38, 0x31, 0x9f, 0xce, 0xd4, 0xf8, 0xe4, 0x70, 0xf9, 0x68, 0x9c, 0xee, 0xc9, 0xba,
	0xae, 0x1f, 0xc3, 0x50, 0xf5, 0x15, 0x41, 0xba, 0x67, 0xc5, 0xb8, 0x85, 0x58, 0xab, 0x3c, 0x2a,
	0xa3, 0x3a, 0x91, 0xb1, 0x56, 0x78, 0x07, 0xff, 0x9c, 0x76, 0x67, 0xca, 0xe3, 0x32, 0xaa, 0x37,
	0x32, 0x5c, 0xb0, 0x84, 0x4c, 0x91, 0x3d, 0x1a, 0x3d, 0x3a, 0xcd, 0x43, 0x9e, 0xf8, 0xb7, 0xeb,
	0x08, 0x9f, 0x61, 0x6d, 0xa8, 0xd7, 0x83, 0x22, 0x93, 0xa7, 0x65, 0x54, 0x67, 0x6d, 0x21, 0x82,
	0x84, 0x58, 0x24, 0xc4, 0x7e, 0x91, 0x90, 0x3f, 0xb3, 0xd5, 0x2b, 0xfc, 0x7f, 0x33, 0xd4, 0x39,
	0x92, 0xf4, 0x79, 0x21, 0xeb, 0xf0, 0x06, 0x92, 0x6e, 0xd4, 0xde, 0x68, 0x23, 0xe7, 0x23, 0xde,
	0x43, 0x3a, 0xd7, 0xf4, 0x46, 0x59, 0xbb, 0x16, 0xd3, 0x4e, 0xcc, 0xea, 0xd2, 0xa7, 0x55, 0x0b,
	0xdb, 0x05, 0x60, 0x47, 0x1e, 0x2c, 0xfd, 0x41, 0x08, 0x25, 0xe3, 0xa5, 0x64, 0xfb, 0x02, 0xd9,
	0x4c, 0x78, 0x0f, 0x7b, 0xc3, 0x06, 0x56, 0x01, 0x81, 0xb7, 0x33, 0xfc, 0x97, 0x4f, 0x81, 0xd7,
	0x51, 0xf8, 0xe1, 0xb0, 0xf2, 0x95, 0x9e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x72, 0xfc,
	0xeb, 0x7f, 0x01, 0x00, 0x00,
}
