GRPC_PORT = "0.0.0.0.9090"
POSTGRES_HOST = "0.0.0.0:5432"
POSTGRES_DATABASE = "grpcrud"
POSTGRES_USER_USERNAME = "read_write_user"
POSTGRES_USER_PASSWORD = "<INSERT PASSWORD>"
SERVER = "0.0.0.0:9090"
